#!/usr/bin/env node
/*
 * Compile the JSX source files into browser-ready JavaScript for GitHub Pages.
 * Runtime pages must not load @babel/standalone; that keeps first paint fast and reliable.
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const https = require('https');

const BABEL_URL = 'https://unpkg.com/@babel/standalone@7.29.0/babel.min.js';

function get(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        get(new URL(res.headers.location, url).toString()).then(resolve, reject);
        return;
      }
      if (res.statusCode !== 200) {
        reject(new Error(`GET ${url} failed: ${res.statusCode}`));
        res.resume();
        return;
      }
      const chunks = [];
      res.on('data', chunk => chunks.push(chunk));
      res.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    }).on('error', reject);
  });
}

async function loadBabel() {
  const source = await get(BABEL_URL);
  const sandbox = { module: { exports: {} } };
  sandbox.exports = sandbox.module.exports;
  sandbox.globalThis = sandbox;
  sandbox.window = sandbox;
  sandbox.self = sandbox;
  vm.createContext(sandbox);
  vm.runInContext(source, sandbox, { filename: 'babel-standalone.js' });
  const Babel = sandbox.module.exports && Object.keys(sandbox.module.exports).length
    ? sandbox.module.exports
    : sandbox.Babel;
  if (!Babel || typeof Babel.transform !== 'function') {
    throw new Error('Unable to load Babel standalone');
  }
  return Babel;
}

function read(file) {
  return fs.readFileSync(file, 'utf8');
}

function compile(Babel, outFile, sources) {
  const input = sources.map(([label, code]) => `\n/* ${label} */\n${code}\n`).join('\n');
  const result = Babel.transform(input, {
    presets: ['react'],
    comments: false,
    compact: false,
    sourceType: 'script',
  }).code;
  const banner = '/* Generated by scripts/build-js.js from JSX sources. Do not edit directly. */\n';
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, banner + result + '\n');
}

async function main() {
  const Babel = await loadBabel();

  compile(Babel, 'assets/js/landing.js', [
    ['parts/Header.jsx', read('parts/Header.jsx')],
    ['parts/Visuals.jsx', read('parts/Visuals.jsx')],
    ['parts/Sections.jsx', read('parts/Sections.jsx')],
    ['parts/App.jsx', read('parts/App.jsx')],
  ]);

  const subShared = read('parts/SubShared.jsx');
  for (const [source, js] of [
    ['parts/pages/AccountPage.jsx', 'account.js'],
    ['parts/pages/DocsPage.jsx', 'docs.js'],
    ['parts/pages/DownloadPage.jsx', 'download.js'],
    ['parts/pages/PaymentPage.jsx', 'payment.js'],
    ['parts/pages/ResultPage.jsx', 'result.js'],
    ['parts/pages/StorePage.jsx', 'store.js'],
  ]) {
    compile(Babel, `assets/js/${js}`, [
      ['parts/SubShared.jsx', subShared],
      [source, read(source)],
    ]);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
